# =====================================
#               SOMBRAS
# =====================================

shadow = true;
shadow-radius = 10;
shadow-opacity = 0.5;
shadow-offset-x = -10;
shadow-offset-y = -10;

# Apps que no tendran sombra

shadow-exclue = [
    "class_g = 'Rofi'",
    "class_g = 'slop'",
    "_GTK_FRAME_EXTENTS@:c"
];

# ====================================
#               TRANSPARENCIA
# ====================================

inactive-opacity = 0.9;
active-opacity = 1.0;
frame-opacity = 1.0;

# Apps que siempre seran opacas
opacity-rule = [
    "100:class_g = 'firefox'",
    "100:class_g = 'mpv'"
];


# ====================================
#               BLUR
# ====================================

blur-background = true;
blur-method = "dual_kawase";
blur-strength = 5;

blur-exclude = [
    "class_g = 'slop'"
];


# ======================================
#               RENDIMIENTO
# ======================================

backend = "glx";
vsync = true;
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
use-damage = true;

# ======================================
#               ANIMACIONES
# ======================================

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;
